version: "3"

services:
  anonymouse-postgres:
    container_name: anonymouse-postgres
    image: postgres:12.0
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - "./server/.env"
    volumes:
      - anonymouse-postgres:/var/lib/postgres/data

volumes:
  anonymouse-postgres:
